version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      # added specifically for github action
      POSTGRES_DB: tdm
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  postgres-ui:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

  # https://stackoverflow.com/questions/45171564/using-vault-with-docker-compose-file
  vault:
    image: vault:1.7.1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8300
    cap_add:
      - IPC_LOCK
    ports:
      - 8300:8300

volumes:
  postgres:
